var globalLanguagePack = {
    "loading.tiles": "Loading...",
    "sharing.shareTitle": "Share page",
    "sharing.firstPage": "First",
    "sharing.currentPage": "Current",
    "sharing.email": "Email",
    "sharing.facebook": "Facebook",
    "sharing.twitter": "Twitter",
    "sharing.linkedIn": "LinkedIn",
    "sharing.fromAddress": "From",
    "sharing.toAddress": "To",
    "sharing.fromAddressPlaceholder": "me@example.com",
    "sharing.toAddressPlaceholder": "friend@example.com",
    "sharing.comments": "Comment",
    "sharing.cancel": "Cancel",
    "sharing.send": "Send",
    "sharing.close": "Close",
    "sharing.contactingServer": "Contacting server...",
    "sharing.genericError": "An error occurred contacting the server",
    "sharing.errors.fromEmailInvalid": "The from email address was not a valid email address",
    "sharing.errors.toEmailInvalid": "The to email address was not a valid email address",
    "sharing.errors.emailError": "This edition cannot be sent to the requested email address at this time",
    "sharing.errors.error": "This edition cannot be shared with the requested site at this time",
    "sharing.errors.notLive": "The edition that you are trying to share is not live",

    "login.forgottenPassword": "Forgotten your password?",
    "login.login": "Login",
    "login.gotoNextFreePage": "Go to the next free page",
    "login.reset.popup": "Error opening new window. Pop up blocking must be turned off to see the reset password page",
    "login.reset.genericError": "An error occurred contacting the server",
    "login.reset.sent": "We have sent a password reset email to your email address",
    "login.reset.contactingServer": "Contacting server...",
    "login.reset.errors.no_email": "Please enter your email address so that we can send the password reset email",
    "login.reset.errors.email_not_found": "We were unable to send a reset email, please check that your email address is correct",
    "login.reset.errors.email_invalid": "We were unable to send a reset email, please check that your email address is correct",
    "login.reset.errors.unavailable": "An error occurred sending the reset email, please try again",
    "login.reset.errors.unknown_error": "An error occurred sending the reset email, please try again",
    "login.auth.genericError": "An error occurred contacting the server",
    "login.auth.errors.failure": "An error occurred during login",
    "login.auth.errors.credentials": "Login failed because the login details provided were not correct, please try again",
    "login.auth.errors.readerLimit": "Login failed because the number of devices that this subscription login has been used on has been exceeded",
    "login.auth.errors.dateRestriction": "Login failed because this edition is not covered by the dates of your subscription",
    "login.auth.errors.userNotAuthenticated": "Login failed because the login details provided do not have access to this edition",
    "login.contactingServer": "Contacting server...",
    "login.explanation": "This edition requires a subscription to view, please login",
    "login.libraryExplanation": "Please login to your Yudu Free account to view the next page",
    "login.libraryPasswordExplanation": "A password is required to view the next page. This should have been given to you by your content provider.",
    "login.username": "Username",
    "login.password": "Password",

    "dataCollection.skip": "Skip",
    "dataCollection.submit": "Submit",
    "dataCollection.dontShowAgain": "Don't show this message again",
    "dataCollection.email": "Email address",
    "dataCollection.invalidEmail": "Please enter a valid email address",
    "dataCollection.infoLink": "Further details",

    "userPreferences.pageTurn": "Use animated page transitions",

    "info.title": "Navigation Guide",
    "info.mouseText": "click: menu/interact | scroll: zoom | click & drag: pan",
    "info.touchText": "tap: menu/interact | pinch: zoom | hold & drag: pan",
    "info.doNotShowAgain": "Don't show this information again",
    "info.close": "Close",

    "info.unableToOpenLink.message": "It looks like you tried to follow a link, but we could not confirm if it opened correctly. Do you want to navigate there directly instead?",
    "info.unableToOpenLink.back": "Cancel",
    "info.unableToOpenLink.forward": "Follow link",

    "thumbnails.page": "Page",
    "thumbnails.intro": "Introduction",
    "thumbnails.segments.primary": "Pages",
    "thumbnails.segments.bookmarks": "Bookmarks",
    "thumbnails.segments.pageHighlights": "Highlights",
    "thumbnails.segments.notes": "Notes",

    "message.close": "Close",

	"messages.popup": "Error opening new window. Pop up blocking must be turned off to share this page",

    "criticalError": "An error occurred, please refresh and try again",

    "phoneview.criticalError": "An error occurred trying to open PhoneView, please try again",

    "search.local": "Document",
    "search.archive": "Archive",
    "search.placeholder": "Search edition",
    "search.noResults": "0 results",
    "search.searching": "Searching...",
    "search.close": "Close",
    "search.page": "Page: ",

    "ugc.syncError": "Unable to synchronise annotations. Changes to annotations will only be saved locally.",
    "ugc.sync.subscriberError": "Unable to verify details to synchronise annotations. Annotations will only be saved locally.",
    "ugc.login.explanation": "Subscribers can synchronise their annotations if they login.",
    "ugc.syncMerge.message": "Offline annotations have been detected. If you wish, you can merge them into your existing annotations. Otherwise you can discard them.",
    "ugc.syncMerge.merge": "Merge",
    "ugc.syncMerge.discard": "Discard",

    "bookmarks.introPageWarning": "You cannot bookmark the intro page.",

    "highlights.cancel": "Cancel",
    "highlights.undo": "Undo",
    "highlights.clearAll": "Clear All",
    "highlights.redo": "Redo",
    "highlights.save": "Save",
    "highlights.introPageWarning": "You cannot create highlights on the intro page.",

    "note.createNoteMessage": "Tap to add note",
    "note.cancel": "Cancel",
    "note.save": "OK",
    "note.delete": "Delete",
    "note.browse": "Browse",
    "note.ok": "OK",
    "note.deleteNoteMessage": "Are you sure you want to delete this note?",
    "note.firstNoteCreated": "You have just created a note. Tap to open or edit it, or touch and hold to move it.",
    "note.introPageWarning": "You cannot create notes on the intro page.",

    "notes.browse.error": "A problem has occurred while updating the notes browse view.",
    "notes.browse.modificationWarning": "The note you were browsing may have been deleted or modified remotely.",

    "orderForm.title": "Order Form",
    "orderForm.productCode": "Product Code",
    "orderForm.description": "Description",
    "orderForm.quantity": "Quantity",
    "orderForm.itemPrice": "Item Price",
    "orderForm.price": "Price",
    "orderForm.removeItem": "Remove",
    "orderForm.removeAllItems": "Remove All",
    "orderForm.noItems": "There are no items in your cart",
    "orderForm.totalPrice": "Total",
    "orderForm.dismissOrderForm": "Continue Shopping",
    "orderForm.send": "Send Order",
    "orderForm.download": "Download Cart to CSV",
    "orderForm.next": "Next >",
    "orderForm.previous": "< Previous",
    "orderForm.genericError": "An error occurred contacting the server",
    "orderForm.success": "Your order has been successfully sent.",
    "orderForm.invalidEmail": "Please use a valid email address",
    "orderForm.missingDetails": "Please fill out all mandatory fields",
    "orderForm.error": "Your order could not be sent at this time. Please try again later.",
    "orderForm.deliveryDetails.name": "Name*",
    "orderForm.deliveryDetails.phone": "Phone*",
    "orderForm.deliveryDetails.email": "Email*",
    "orderForm.deliveryDetails.accountNumber": "AccountNumber",
    "orderForm.deliveryDetails.poNumber": "PO Number",
    "orderForm.deliveryDetails.companyName": "Company Name",
    "orderForm.deliveryDetails.billingAddress": "Billing Address",
    "orderForm.deliveryDetails.deliveryAddress": "Delivery Address",
    "orderForm.deliveryDetails.deliveryDetailsDeliveryAddressSameAsBillingAddress": "Same as Billing Address?",
    "orderForm.deliveryDetails.address1": "Address 1*",
    "orderForm.deliveryDetails.address2": "Address 2",
    "orderForm.deliveryDetails.city": "City / Town*",
    "orderForm.deliveryDetails.state": "State / Province*",
    "orderForm.deliveryDetails.postCode": "Post / Zip Code*",
    "orderForm.deliveryDetails.country": "Country*",
    "orderForm.deliveryDetails.additionalInformation": "Additional Information",

    "gaTrackerConsent.message": "This edition uses Google Analytics in order to collect anonymised information about how this edition is read (such as how many unique people viewed each page). By clicking Accept you agree to our use of cookies and similar technologies in order to provide this service.",
    "gaTrackerConsent.accept": "Accept",
    "gaTrackerConsent.decline": "Decline"
}
;